name: dummyapp
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  fl_chart: ^0.63.0
  table_calendar: ^3.0.0
  file_picker: ^9.0.0
  

  cupertino_icons: ^1.0.8
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/data/community.json
    - lib/assets/images/
    - lib/assets/data/assignment.json
    - lib/assets/data/scores.json
    - lib/assets/data/news.json
    - lib/assets/images/news/image1.jpg
    - lib/assets/images/news/image2.jpeg
    - lib/assets/images/news/image3.jpeg
    - lib/assets/data/notification.json
    - lib/assets/data/students.json
    - lib/assets/data/doubtChat.json

  fonts:
    - family: CustomFont
      fonts:
        - asset: lib\assets\fonts\Technor-Variable.ttf
